apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pr-mas-deploy-
  namespace: default
spec:
  pipelineRef:
    name: mas-devops-deploy
  params:
    - name: uds-email
      value: "dev-techzone@ibm.com"
    - name: uds-firstname
      value: "TechZone"
    - name: uds-lastname
      value: "Developer"
    - name: use-letsencrypt-certs
      value: "true"
    - name: tlscert-secret
      value: "user-serving-cert-000"
    - name: tlscert-namespace
      value: "openshift-kube-apiserver"
    - name: ibm-entitlement-key
      value: "false"
    - name: license-file-secret-name
      value: "false"
    - name: rwx-storageclass
      value: ocs-external-storagecluster-cephfs
    - name: rwo-storageclass
      value: ocs-external-storagecluster-cephfs
    - name: mas-install-core
      value: "true"
    - name: mas-install-manage
      value: "true"
    - name: mas-install-demo-data
      value: "true"
    - name: mas-cp4d-install-cognos
      value: "false"
    - name: mas-install-optimizer
      value: "false"
    - name: mas-install-visualinspection
      value: "false"
    - name: mas-install-iot
      value: "false"
    - name: mas-install-monitor
      value: "false"
    - name: mas-install-predict
      value: "false"
    - name: cpd-platform-components
      value: "false"
    - name: cpd-install-spss
      value: "false"
    - name: cpd-wsl-projectname
      value: "maspredictproject"
    - name: cpd-wml-url
      value: "xxx"
    - name: cpd-admin-url
      value: "xxx"
    - name: cpd-admin-username
      value: "admin"
    - name: cpd-admin-password
      value: "xxx"
    - name: mas-install-aibroker
      value: "false"
    - name: artifactory_username
      value: "xxx"
    - name: artifactory_token
      value: "xxx"
    - name: mas_airbroker_watsonxai_apikey
      value: "xxx"
    - name: mas_airbroker_watsonxai_url
      value: "https://us-south.ml.cloud.ibm.com"
    - name: mas_airbroker_watsonxai_project_id
      value: "xxx"
    - name: mas_aibroker_channel
      value: "9.1.x"
  workspaces:
    - name: ws
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-external-storagecluster-cephfs
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
  timeouts:
    pipeline: "0"
    tasks: "24h"
